export const AgentAIWork = () => {
  return (
    <div className="card">
      <div className="card-header">
        <h2>
          <i className="bi bi-motherboard me-2"></i> Claude to the rescue
        </h2>
      </div>
      <div className="card-body">
        <div className="right">
          <i className="bi bi-braces" style={{ fontSize: "4rem" }}></i>
        </div>

        <p>
          All the hype around AI agents got me thinking about all the repetative
          tasks I'm regularly doing on this and other project sites. So
          willingly I started using the <strong>free</strong> Claude Sonnet 3.5
          model in my codebase. Asking it to review test-coverage and repair
          config issues. I was thoroughly impressed with what I witnessed, not
          just the speed or understanding of the codebase, but also the ability
          to solve the problems and intepret my amateurish prompts.
        </p>

        <div className="left">
          <i className="bi bi-code-slash" style={{ fontSize: "4rem" }}></i>
        </div>

        <p>
          What started as an exercise in experimentation, quickly turned into a
          tool utilisation project. I am now actively using it to try and
          implement Github Actions, to create a <strong>CI/CD pipeline</strong>.
          There are many more improvements I would like to tackle, ones which
          I've put off due to lack of time for research and honest to goodness
          fear. The ability to fail fast and safely recover, using AI Agentic
          tooling is a total game changer for me. I will not let it write css
          for me, nor create Accessible components, as I am an expert in those
          fields. But where I am a novice and without any experience or
          opinions, I will gladly let it take the lead and educate me with it's
          comprehensive descriptions and suggestions.
        </p>

        <div className="left">
          <i
            className="bi bi-universal-access"
            style={{ fontSize: "4rem" }}
          ></i>
        </div>

        <p>
          Words of caution are <strong>not misplaced</strong> - I have seen with
          my own four eyes the incredible mess AI can create with poor prompts,
          no guardrails and an ignorance of compliance requirements. The
          'quality' of CSS and HTML generated by AI is often poor, or worse. But
          using it as a learning tool, can carry a risk of learning poor habits,
          so I am cautious of following it blindly for things I have little
          experience of.
        </p>
      </div>
    </div>
  );
};
